export const APPLICATION_PLATFORM_STATUS_ATTRIBUTE = 'data-platform-status';

export const APPLICATION_PLATFORM_READY_STATUS = 'ready';

export const APPLICATION_PLATFORM_READY_SELECTOR = `[${APPLICATION_PLATFORM_STATUS_ATTRIBUTE}="${APPLICATION_PLATFORM_READY_STATUS}"]`;
